const sizes = [
  { size_id: 1, size_value: "S" },
  { size_id: 2, size_value: "M" },
  { size_id: 3, size_value: "L" },
  { size_id: 4, size_value: "XL" },
  { size_id: 5, size_value: "XXL" },
  { size_id: 6, size_value: "128GB" },
  { size_id: 7, size_value: "256GB" },
  { size_id: 8, size_value: "512GB" },
  { size_id: 9, size_value: "1TB" },
  { size_id: 10, size_value: "24 inches" },
  { size_id: 11, size_value: "32 inches" },
  { size_id: 12, size_value: "36 inches" },
  { size_id: 13, size_value: "42 inches" },
  { size_id: 14, size_value: "50 inches" },
  { size_id: 15, size_value: "55 inches" },
  { size_id: 16, size_value: "65 inches" },
  { size_id: 17, size_value: "27 inches" },
  { size_id: 18, size_value: "45 mm" },
  { size_id: 19, size_value: "41 mm" },
  { size_id: 20, size_value: "2" },
  { size_id: 21, size_value: "3" },
  { size_id: 22, size_value: "1000XM5" },
  { size_id: 23, size_value: "10cm x 7cm" },
  { size_id: 24, size_value: "Mini" },
  { size_id: 25, size_value: "50 x 50" },
];
;
const colors = [
  { color_id: 1, color_value: "Grey" },
  { color_id: 2, color_value: "Yellow" },
  { color_id: 3, color_value: "Dark Blue" },
  { color_id: 4, color_value: "Red" },
  { color_id: 5, color_value: "Blue" },
  { color_id: 6, color_value: "White" },
  { color_id: 7, color_value: "Black" },
  { color_id: 8, color_value: "Pink" },
  { color_id: 9, color_value: "Green" },
  { color_id: 10, color_value: "Dark Green" },
  { color_id: 11, color_value: "Brown" },
  { color_id: 12, color_value: "Gold" },
  { color_id: 13, color_value: "Multi Color" },
];

export const fakeData = {
  sizes,
  colors,
}
