export const currentUsers = [
  {
    id: 1,
    name: "TV",
    discription: "abc",
    sold: 1,
    min_price: 100,
    max_price: 200,
    best_seller: true,
    porpular: true,
    rate: 4.5,
    top_deal: true,
    official: true,
    discount: 10,
  },
  {
    id: 2,
    name: "Wireless Earbuds",
    discription: "A versatile tool for everyday listening.",
    sold: 5,
    min_price: 150,
    max_price: 300,
    best_seller: false,
    porpular: false,
    rate: 4.2,
    top_deal: false,
    official: false,
    discount: 15,
  },
  {
    id: 3,
    name: "Smartwatch Series 5",
    discription: "High-quality smartwatch for all your needs.",
    sold: 3,
    min_price: 75,
    max_price: 150,
    best_seller: true,
    porpular: true,
    rate: 3.9,
    top_deal: true,
    official: true,
    discount: 5,
  },
  {
    id: 4,
    name: "4K Action Camera",
    discription: "Top-notch camera for adventure enthusiasts.",
    sold: 10,
    min_price: 200,
    max_price: 400,
    best_seller: true,
    porpular: true,
    rate: 4.8,
    top_deal: true,
    official: true,
    discount: 20,
  },
  {
    id: 5,
    name: "Bluetooth Speaker",
    discription: "Professional-grade speaker at a great price.",
    sold: 0,
    min_price: 50,
    max_price: 100,
    best_seller: false,
    porpular: false,
    rate: 3.5,
    top_deal: false,
    official: false,
    discount: 0,
  },
  {
    id: 6,
    name: "Smart Home Hub",
    discription: "Advanced technology for modern homes.",
    sold: 8,
    min_price: 125,
    max_price: 250,
    best_seller: true,
    porpular: true,
    rate: 4.6,
    top_deal: true,
    official: true,
    discount: 10,
  },
  {
    id: 7,
    name: "Noise Cancelling Headphones",
    discription: "Deluxe headphones for premium sound.",
    sold: 2,
    min_price: 60,
    max_price: 120,
    best_seller: false,
    porpular: false,
    rate: 3.8,
    top_deal: false,
    official: false,
    discount: 5,
  },
  {
    id: 8,
    name: "Portable Charger",
    discription: "Superb charger with unmatched quality.",
    sold: 6,
    min_price: 175,
    max_price: 350,
    best_seller: true,
    porpular: true,
    rate: 4.7,
    top_deal: true,
    official: true,
    discount: 12,
  },
  {
    id: 9,
    name: "Fitness Tracker",
    discription: "Ultimate performance for all your fitness needs.",
    sold: 4,
    min_price: 90,
    max_price: 180,
    best_seller: false,
    porpular: true,
    rate: 4.0,
    top_deal: false,
    official: true,
    discount: 8,
  },
  {
    id: 10,
    name: "Laptop Stand",
    discription: "Ergonomic stand for serious users.",
    sold: 7,
    min_price: 140,
    max_price: 280,
    best_seller: true,
    porpular: true,
    rate: 4.3,
    top_deal: true,
    official: true,
    discount: 10,
  },
  {
    id: 11,
    name: "Gaming Mouse",
    discription: "High-precision mouse for quick tasks.",
    sold: 9,
    min_price: 130,
    max_price: 260,
    best_seller: true,
    porpular: false,
    rate: 4.4,
    top_deal: true,
    official: false,
    discount: 7,
  },
];
